### ISSUE TITLE
Non-obvious syntax error

### ISSUE THREAD

**Issue by kalashnikovisme** [ruby-next/ruby-next#105]
Unfortunately, I'm sure about this issue. Does it belong to ruby-next or to [parser](https://github.com/whitequark/parser)? That's why it's a feedback.

Ruby 3.1.2

we have this 2 lines

*some_spec.rb*
```ruby
mock_board_api_request board, query: # line 5
mock_lists_api_request lists, query: # line 6
```

Definitely, it's syntax error. We have this error message with ruby-next. It doesn't have info about file and line with syntax error.

```
SyntaxError:
  unexpected token tIDENTIFIER
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language/parser.rb:43:in `rescue in parse'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language/parser.rb:36:in `parse'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language.rb:160:in `block in rewrite'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language.rb:156:in `each'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language.rb:156:in `inject'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language.rb:156:in `rewrite'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language.rb:103:in `transform'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language/runtime.rb:34:in `transform'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language/runtime.rb:25:in `load'
# /home/pavel/.rvm/gems/ruby-3.1.2/gems/ruby-next-core-0.15.3/lib/ruby-next/language/runtime.rb:112:in `load'
# ------------------
# --- Caused by: ---
# Parser::SyntaxError:
#   unexpected token tIDENTIFIER
#   /home/pavel/.rvm/gems/ruby-3.1.2/gems/parser-3.1.3.0/lib/parser/diagnostic/engine.rb:72:in `process'
```

Without ruby-next we have this message. Looks like it's better message
```
some_spec.rb:6: syntax error, unexpected string literal, expecting `do' or '{' or '('
```

Is it abour ruby-next or about parser?

**Comment by palkan** [comment]
> Definitely, it's syntax error,

it's actually not, it's a valid Ruby 3.1 syntax.

But I see your point. I think, we should figure out how to make Parser SyntaxError look more like a native SyntaxError

**Comment by kalashnikovisme** [comment]
@palkan 🤔

By the way, why do I have error at this case? Will check it one more time soon.

Thanks!

**Comment by palkan** [comment]
> why do I have error at this case? 

I don't know 🤷‍♂️ the code you provided in the description looks valid to me
