### ISSUE TITLE
ruby-next-core 0.13.0: No such file or directory @ rb_check_realpath_internal

### ISSUE THREAD

**Issue by Mayurifag** [ruby-next/ruby-next#79]
## What did you do?
I was updating my dependencies on https://github.com/Mayurifag/rails-vue-fullstack-ultimate-template/tree/update-deps project. After making bump to ruby 3.0.2 and `bundle update` I've got an issue with `anyway_config` and its dependence `ruby-next-core-0.13.0/`

After trying to do anything rails related, I've got this:

```sh
Creating rails-vue-fullstack-ultimate-template_backend_run ... done
/bundle/ruby/3.0.0/gems/ruby-next-core-0.13.0/lib/ruby-next/language/setup.rb:53:in `realpath': No such file or directory @ rb_check_realpath_internal - /bundle/ruby/3.0.0/gems/rails-6.1.4.1/lib (Errno::ENOENT)
	from /bundle/ruby/3.0.0/gems/ruby-next-core-0.13.0/lib/ruby-next/language/setup.rb:53:in `realpath'
	from /bundle/ruby/3.0.0/gems/ruby-next-core-0.13.0/lib/ruby-next/language/setup.rb:53:in `block in setup_gem_load_path'
	from /bundle/ruby/3.0.0/gems/ruby-next-core-0.13.0/lib/ruby-next/language/setup.rb:52:in `find_index'
	from /bundle/ruby/3.0.0/gems/ruby-next-core-0.13.0/lib/ruby-next/language/setup.rb:52:in `setup_gem_load_path'
	from /bundle/ruby/3.0.0/gems/anyway_config-2.1.0/lib/anyway_config.rb:6:in `<main>'
	from /bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       ...
```

## Additional context

When I've added `gem "ruby-next-core", "< 0.13.0"` into gemfile, it probably fixed the issue.

## Environment

**Ruby version**: 3.0.2 (not 2.x as in github template)

**Comment by palkan** [comment]
Thanks for the report! Fixed in 0.13.1.
